/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Html5QrCode: typeof import('./src/components/html5QrCode.vue')['default']
    InputWidgetScan: typeof import('./src/components/input-widget-sub/input-widget-scan.vue')['default']
    RxingWasm: typeof import('./src/components/rxing-wasm.vue')['default']
    ShowTooltip: typeof import('./src/components/show-tooltip/show-tooltip.vue')['default']
    ZTable: typeof import('./src/components/zTable/index.vue')['default']
  }
}
